version: "3.9"

services:
  clickhouse:
    build:
      context: .
      dockerfile: clickhouse.Dockerfile
    environment:
      CLICKHOUSE_DB: "metric"
    restart: always
    volumes:
      - clickhouse:/var/lib/clickhouse/
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    depends_on:
      - clickhouse
    ports:
      - "8081:8081"
    environment:
      DB_ADDR: 'clickhouse:9000'
      DB_NAME: 'metric'

volumes:
  clickhouse:
    driver: local