// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: events/update_flipper_end.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateFlipperEnd_UpdateStatus int32

const (
	UpdateFlipperEnd_COMPLETED       UpdateFlipperEnd_UpdateStatus = 0
	UpdateFlipperEnd_CANCELED        UpdateFlipperEnd_UpdateStatus = 1
	UpdateFlipperEnd_FAILED_DOWNLOAD UpdateFlipperEnd_UpdateStatus = 2
	UpdateFlipperEnd_FAILED_PREPARE  UpdateFlipperEnd_UpdateStatus = 3
	UpdateFlipperEnd_FAILED_UPLOAD   UpdateFlipperEnd_UpdateStatus = 4
	UpdateFlipperEnd_FAILED          UpdateFlipperEnd_UpdateStatus = 5
)

// Enum value maps for UpdateFlipperEnd_UpdateStatus.
var (
	UpdateFlipperEnd_UpdateStatus_name = map[int32]string{
		0: "COMPLETED",
		1: "CANCELED",
		2: "FAILED_DOWNLOAD",
		3: "FAILED_PREPARE",
		4: "FAILED_UPLOAD",
		5: "FAILED",
	}
	UpdateFlipperEnd_UpdateStatus_value = map[string]int32{
		"COMPLETED":       0,
		"CANCELED":        1,
		"FAILED_DOWNLOAD": 2,
		"FAILED_PREPARE":  3,
		"FAILED_UPLOAD":   4,
		"FAILED":          5,
	}
)

func (x UpdateFlipperEnd_UpdateStatus) Enum() *UpdateFlipperEnd_UpdateStatus {
	p := new(UpdateFlipperEnd_UpdateStatus)
	*p = x
	return p
}

func (x UpdateFlipperEnd_UpdateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateFlipperEnd_UpdateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_events_update_flipper_end_proto_enumTypes[0].Descriptor()
}

func (UpdateFlipperEnd_UpdateStatus) Type() protoreflect.EnumType {
	return &file_events_update_flipper_end_proto_enumTypes[0]
}

func (x UpdateFlipperEnd_UpdateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateFlipperEnd_UpdateStatus.Descriptor instead.
func (UpdateFlipperEnd_UpdateStatus) EnumDescriptor() ([]byte, []int) {
	return file_events_update_flipper_end_proto_rawDescGZIP(), []int{0, 0}
}

type UpdateFlipperEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateFrom   string                        `protobuf:"bytes,1,opt,name=update_from,json=updateFrom,proto3" json:"update_from,omitempty"`
	UpdateTo     string                        `protobuf:"bytes,2,opt,name=update_to,json=updateTo,proto3" json:"update_to,omitempty"`
	UpdateId     int64                         `protobuf:"varint,3,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	UpdateStatus UpdateFlipperEnd_UpdateStatus `protobuf:"varint,4,opt,name=update_status,json=updateStatus,proto3,enum=metric.events.UpdateFlipperEnd_UpdateStatus" json:"update_status,omitempty"`
}

func (x *UpdateFlipperEnd) Reset() {
	*x = UpdateFlipperEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_update_flipper_end_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlipperEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlipperEnd) ProtoMessage() {}

func (x *UpdateFlipperEnd) ProtoReflect() protoreflect.Message {
	mi := &file_events_update_flipper_end_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlipperEnd.ProtoReflect.Descriptor instead.
func (*UpdateFlipperEnd) Descriptor() ([]byte, []int) {
	return file_events_update_flipper_end_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateFlipperEnd) GetUpdateFrom() string {
	if x != nil {
		return x.UpdateFrom
	}
	return ""
}

func (x *UpdateFlipperEnd) GetUpdateTo() string {
	if x != nil {
		return x.UpdateTo
	}
	return ""
}

func (x *UpdateFlipperEnd) GetUpdateId() int64 {
	if x != nil {
		return x.UpdateId
	}
	return 0
}

func (x *UpdateFlipperEnd) GetUpdateStatus() UpdateFlipperEnd_UpdateStatus {
	if x != nil {
		return x.UpdateStatus
	}
	return UpdateFlipperEnd_COMPLETED
}

var File_events_update_flipper_end_proto protoreflect.FileDescriptor

var file_events_update_flipper_end_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x66, 0x6c, 0x69, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0xb5, 0x02, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x70, 0x70,
	0x65, 0x72, 0x45, 0x6e, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x51, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c,
	0x69, 0x70, 0x70, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x73, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x4c,
	0x4f, 0x41, 0x44, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f,
	0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x41, 0x49,
	0x4c, 0x45, 0x44, 0x5f, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x42, 0x24, 0x0a, 0x22, 0x63, 0x6f, 0x6d, 0x2e,
	0x66, 0x6c, 0x69, 0x70, 0x70, 0x65, 0x72, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70,
	0x62, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_update_flipper_end_proto_rawDescOnce sync.Once
	file_events_update_flipper_end_proto_rawDescData = file_events_update_flipper_end_proto_rawDesc
)

func file_events_update_flipper_end_proto_rawDescGZIP() []byte {
	file_events_update_flipper_end_proto_rawDescOnce.Do(func() {
		file_events_update_flipper_end_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_update_flipper_end_proto_rawDescData)
	})
	return file_events_update_flipper_end_proto_rawDescData
}

var file_events_update_flipper_end_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_update_flipper_end_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_update_flipper_end_proto_goTypes = []interface{}{
	(UpdateFlipperEnd_UpdateStatus)(0), // 0: metric.events.UpdateFlipperEnd.UpdateStatus
	(*UpdateFlipperEnd)(nil),           // 1: metric.events.UpdateFlipperEnd
}
var file_events_update_flipper_end_proto_depIdxs = []int32{
	0, // 0: metric.events.UpdateFlipperEnd.update_status:type_name -> metric.events.UpdateFlipperEnd.UpdateStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_update_flipper_end_proto_init() }
func file_events_update_flipper_end_proto_init() {
	if File_events_update_flipper_end_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_events_update_flipper_end_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFlipperEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_update_flipper_end_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_update_flipper_end_proto_goTypes,
		DependencyIndexes: file_events_update_flipper_end_proto_depIdxs,
		EnumInfos:         file_events_update_flipper_end_proto_enumTypes,
		MessageInfos:      file_events_update_flipper_end_proto_msgTypes,
	}.Build()
	File_events_update_flipper_end_proto = out.File
	file_events_update_flipper_end_proto_rawDesc = nil
	file_events_update_flipper_end_proto_goTypes = nil
	file_events_update_flipper_end_proto_depIdxs = nil
}
