name: 'Deploy'

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 'Set image tag'
        id: tag
        run: |
          IMAGE_TAG="0.0.0"
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            REF=${{ github.ref }};
            TAG_FULL=${REF#refs/*/};
            IMAGE_TAG=${TAG_FULL//\//_};
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: 'Build and push go-metric'
        id: docker_build_app
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/flipperdevices/go-metric:${{steps.tag.outputs.image_tag}}
          context: .
          file: app.Dockerfile

      - name: 'Build and push Clickhouse'
        id: docker_build_clickhouse
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/flipperdevices/metric-clickhouse:${{steps.tag.outputs.image_tag}}
          context: .
          file: clickhouse.Dockerfile

      - name: 'Print image digest'
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: 'Trigger k8s to use new image'
        if: ${{ steps.tag.outputs.image_tag != '0.0.0' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ${{ secrets.INFRASTRUCTURE_REPO }}
          token: ${{ secrets.K8S_GITHUB_PAT }}
          event-type: metric-flipperdevices-com-deploy
          client-payload: '{"image_tag": "${{steps.tag.outputs.image_tag}}"}'
